---
- hosts: webservers
  become: yes
  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create a simple index.html file
      copy:
        dest: /var/www/html/index.html
        content: "Hello World from Ansible!"
